import assert from "node:assert/strict";
import { describe, it } from "node:test";
import { mkdtemp, readFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { DESIGN_CONTRACT_VERSION, validateBlueprint } from "../src/blueprint.js";
import { buildBlueprintDraftReport, draftBlueprint, writeBlueprintDraft } from "../src/blueprint-draft.js";
import { buildDesignPlan } from "../src/design-plan.js";
import { buildDiscoveryDb } from "../src/discovery-db.js";

async function loadJson(url) {
  return JSON.parse(await readFile(url, "utf8"));
}

describe("blueprint draft", () => {
  it("drafts a valid blueprint from discovery db plus user need", async () => {
    const manifest = await loadJson(new URL("../examples/support-triage.discovery.json", import.meta.url));
    const need = await loadJson(new URL("../examples/support-triage.need.json", import.meta.url));
    const discoveryDb = buildDiscoveryDb(manifest, { manifestPath: "examples/support-triage.discovery.json" });
    const blueprint = draftBlueprint(discoveryDb, need, { target: "openclaw" });
    const validation = validateBlueprint(blueprint);
    assert.equal(validation.ok, true, validation.errors.join("\n"));
    assert.equal(blueprint.agent_id, "support-triage");
    assert.equal(blueprint.runtime, "openclaw");
    assert.equal(blueprint.status, "draft");
    assert.deepEqual(blueprint.design_contract?.provenance, {
      source: "agentmo-stage2",
      reviewed: true,
      review_ref: "blueprint-draft:agentmo.discovery-db.v1+agentmo.user-need.v1",
      contract_version: DESIGN_CONTRACT_VERSION,
      notes:
        "Generated by AgentMo Stage 2 from validated discovery-db and user-need artifacts; this is an admission record only, not runtime/domain certification.",
    });
    assert.equal(blueprint.tools.length, 3);
    assert.equal(blueprint.pipeline.discover.data_sources.length, 3);
    assert.equal(
      blueprint.governance.policies.includes(
        "AgentMo-generated blueprints must preserve reviewed discovery/user-need provenance; Stage 3 admission is by valid design contract.",
      ),
      true,
    );
    assert.equal(blueprint.governance.policies.includes("discover-plan-produce order is mandatory"), false);

    const dir = await mkdtemp(path.join(tmpdir(), "agentmo-blueprint-draft-"));
    const file = await writeBlueprintDraft(path.join(dir, "support-triage.agentmo.json"), blueprint);
    const saved = JSON.parse(await readFile(file, "utf8"));
    assert.equal(saved.agent_id, "support-triage");
  });

  it("rejects mismatched discovery and need agent ids", async () => {
    const manifest = await loadJson(new URL("../examples/support-triage.discovery.json", import.meta.url));
    const need = await loadJson(new URL("../examples/support-triage.need.json", import.meta.url));
    need.agent_id = "other-agent";
    const discoveryDb = buildDiscoveryDb(manifest);
    assert.throws(() => draftBlueprint(discoveryDb, need, { target: "openclaw" }), /does not match user-need/u);
  });

  it("drafts from a validated design-plan without embedding the full evidence map", async () => {
    const manifest = await loadJson(new URL("../examples/support-triage.discovery.json", import.meta.url));
    const need = await loadJson(new URL("../examples/support-triage.need.json", import.meta.url));
    const discoveryDb = buildDiscoveryDb(manifest, { manifestPath: "examples/support-triage.discovery.json" });
    const designPlan = buildDesignPlan(discoveryDb, need, { target: "openclaw" });

    const blueprint = draftBlueprint(discoveryDb, need, { target: "openclaw", designPlan, designPlanPath: "agentmo-design-plan.json" });
    const validation = validateBlueprint(blueprint);
    assert.equal(validation.ok, true, validation.errors.join("\n"));
    assert.equal(blueprint.design_contract.provenance.review_ref, "design-plan:agentmo-design-plan.json");
    assert.equal(blueprint.pipeline.plan.planning_inputs.includes("agentmo-design-plan.json"), true);
    assert.equal("evidenceMap" in blueprint, false);
    assert.equal(JSON.stringify(blueprint).includes("requirementsTrace"), false);
  });

  it("rejects invalid or mismatched design-plan input", async () => {
    const manifest = await loadJson(new URL("../examples/support-triage.discovery.json", import.meta.url));
    const need = await loadJson(new URL("../examples/support-triage.need.json", import.meta.url));
    const discoveryDb = buildDiscoveryDb(manifest, { manifestPath: "examples/support-triage.discovery.json" });
    const designPlan = buildDesignPlan(discoveryDb, need, { target: "openclaw" });

    assert.throws(() => draftBlueprint(discoveryDb, need, { target: "agentmo", designPlan }), /target runtime/i);

    const notOk = structuredClone(designPlan);
    notOk.ok = false;
    assert.throws(() => draftBlueprint(discoveryDb, need, { target: "openclaw", designPlan: notOk }), /design-plan ok must be true/i);

    const invalidValidation = structuredClone(designPlan);
    invalidValidation.validation.ok = false;
    assert.throws(() => draftBlueprint(discoveryDb, need, { target: "openclaw", designPlan: invalidValidation }), /design-plan validation.ok must be true/i);

    const wrongAgent = structuredClone(designPlan);
    wrongAgent.agentId = "other-agent";
    assert.throws(() => draftBlueprint(discoveryDb, need, { target: "openclaw", designPlan: wrongAgent }), /agent id/i);
  });

  it("reports blueprint output paths without leaking host absolute paths", async () => {
    const manifest = await loadJson(new URL("../examples/support-triage.discovery.json", import.meta.url));
    const need = await loadJson(new URL("../examples/support-triage.need.json", import.meta.url));
    const discoveryDb = buildDiscoveryDb(manifest, { manifestPath: "examples/support-triage.discovery.json" });
    const blueprint = draftBlueprint(discoveryDb, need, { target: "openclaw" });
    const dir = await mkdtemp(path.join(tmpdir(), "agentmo-blueprint-report-"));
    const report = buildBlueprintDraftReport(blueprint, { blueprintPath: path.join(dir, "support-triage.agentmo.json") });
    assert.equal(report.blueprintPath, "support-triage.agentmo.json");
  });

});
