import { mkdir, readdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { validateBlueprint } from "./blueprint.js";

export const SCAFFOLD_TARGETS = new Set(["agentmo", "openclaw"]);

export async function scaffoldAgent(blueprint, outputDir, options = {}) {
  const target = options.target ?? "agentmo";
  if (!SCAFFOLD_TARGETS.has(target)) {
    throw new Error(`Unknown scaffold target: ${target}. Expected one of: ${Array.from(SCAFFOLD_TARGETS).join(", ")}`);
  }

  const validation = validateBlueprint(blueprint);
  if (!validation.ok) {
    throw new Error(`Cannot scaffold invalid blueprint:\n${validation.errors.map((error) => `- ${error}`).join("\n")}`);
  }

  await assertTargetWritable(outputDir, options.force === true);
  await mkdir(outputDir, { recursive: true });

  const files = buildBaseFiles(blueprint);
  if (target === "openclaw") addOpenClawFiles(files, blueprint, outputDir);

  for (const [relativePath, content] of files.entries()) {
    const filePath = path.join(outputDir, relativePath);
    await mkdir(path.dirname(filePath), { recursive: true });
    await writeFile(filePath, content, "utf8");
  }

  return { outputDir, target, files: Array.from(files.keys()).sort() };
}

async function assertTargetWritable(outputDir, force) {
  let entries = [];
  try {
    entries = await readdir(outputDir);
  } catch (error) {
    if (error && typeof error === "object" && "code" in error && error.code === "ENOENT") return;
    throw error;
  }
  if (entries.length > 0 && !force) {
    throw new Error(`Refusing to scaffold into non-empty directory: ${outputDir}. Pass --force to overwrite generated files.`);
  }
}

function buildBaseFiles(blueprint) {
  const files = new Map([
    ["README.md", renderReadme(blueprint)],
    ["agent_policy.json", JSON.stringify(buildAgentPolicy(blueprint), null, 2) + "\n"],
    [`agents/${blueprint.architecture.main_agent}.md`, renderMainAgent(blueprint)],
    ["evals/CASES.md", renderEvalCases(blueprint)],
    ["evals/RUBRIC.md", renderRubric(blueprint)],
    ["history/VERSION_LEDGER.md", renderVersionLedger(blueprint)],
    ["history/EVIDENCE_INDEX.md", renderEvidenceIndex(blueprint)],
    ["governance/QUALITY_GATES.md", renderQualityGates(blueprint)],
  ]);

  for (const specialist of blueprint.architecture.specialists ?? []) {
    files.set(`agents/${specialist.id}.md`, renderSpecialistAgent(blueprint, specialist));
  }

  return files;
}

function addOpenClawFiles(files, blueprint, outputDir) {
  const workspaceDir = path.join(outputDir, "openclaw", "workspace");
  files.set("openclaw/README.md", renderOpenClawReadme(blueprint));
  files.set("openclaw/RUNBOOK.md", renderOpenClawRunbook(blueprint, workspaceDir));
  files.set("openclaw/runtime_contract.md", renderOpenClawRuntimeContract(blueprint));
  files.set("openclaw/config/openclaw.agent.patch.json", JSON.stringify(buildOpenClawConfigPatch(blueprint, workspaceDir), null, 2) + "\n");
  files.set("openclaw/config/channel-bindings.examples.md", renderOpenClawBindingExamples(blueprint));
  files.set("openclaw/workspace/AGENTS.md", renderOpenClawAgents(blueprint));
  files.set("openclaw/workspace/SOUL.md", renderOpenClawSoul(blueprint));
  files.set("openclaw/workspace/USER.md", renderOpenClawUser(blueprint));
  files.set("openclaw/workspace/TOOLS.md", renderOpenClawTools(blueprint));
  files.set("openclaw/workspace/IDENTITY.md", renderOpenClawIdentity(blueprint));
  files.set(`openclaw/workspace/skills/${blueprint.agent_id}/SKILL.md`, renderOpenClawSkill(blueprint));
  files.set("openclaw/workspace/memory/README.md", renderOpenClawMemoryReadme(blueprint));
}

function buildAgentPolicy(blueprint) {
  return {
    version: "0.1",
    agent_id: blueprint.agent_id,
    runtime: blueprint.runtime,
    runtime_profiles: blueprint.runtime_profiles ?? [],
    status: blueprint.status,
    boundaries: {
      domain: blueprint.domain_genome.domain,
      purpose: blueprint.domain_genome.purpose,
      hard_failures: blueprint.domain_genome.hard_failures,
    },
    routing_modes: blueprint.architecture.routing_modes,
    tools: blueprint.tools.map((tool) => ({
      name: tool.name,
      purpose: tool.purpose,
      allowed_when: tool.allowed_when,
      forbidden_when: tool.forbidden_when,
      evidence_policy: tool.evidence_policy,
    })),
    evidence: blueprint.evidence,
    eval: blueprint.eval,
    governance: blueprint.governance,
  };
}

function renderReadme(blueprint) {
  return `# ${blueprint.agent_id}\n\nGenerated by AgentMother / AgentMo.\n\n## Purpose\n\n${blueprint.domain_genome.purpose}\n\n## AgentMo pipeline\n\n${renderPipeline(blueprint)}\n\n## Runtime\n\n- Primary runtime: ${blueprint.runtime}\n- Main agent: ${blueprint.architecture.main_agent}\n- Status: ${blueprint.status}\n\n## Runtime profiles\n\n${renderRuntimeProfiles(blueprint)}\n\n## Required quality gates\n\n${blueprint.governance.quality_gates.map((gate) => `- ${gate}`).join("\n")}\n\n## Do not release unless\n\n- Discovery data and user needs are captured.\n- Planning artifacts and decision gates are explicit.\n- Tool contracts are explicit.\n- Eval cases exist for each required case class.\n- Evidence artifacts are bounded and auditable.\n- Known risks are recorded.\n`;
}

function renderMainAgent(blueprint) {
  const tools = blueprint.tools.map((tool) => tool.name).join(",");
  return `---\nname: ${blueprint.architecture.main_agent}\ndescription: "Main orchestrator for ${blueprint.agent_id}."\ntools: ${tools}\n---\n\n# ${blueprint.architecture.main_agent}\n\nYou are the main orchestrator for ${blueprint.agent_id}.\n\n## Domain\n\n${blueprint.domain_genome.domain}\n\n## Purpose\n\n${blueprint.domain_genome.purpose}\n\n## Routing modes\n\n${blueprint.architecture.routing_modes.map((mode) => `- ${mode}`).join("\n")}\n\n## Hard failures\n\n${blueprint.domain_genome.hard_failures.map((failure) => `- ${failure}`).join("\n")}\n\n## Evidence policy\n\nUse bounded evidence packets by default. Expand raw artifacts only for explicit audit requests.\n`;
}

function renderSpecialistAgent(blueprint, specialist) {
  return `---\nname: ${specialist.id}\ndescription: "Specialist for ${blueprint.agent_id}: ${specialist.purpose}"\n---\n\n# ${specialist.id}\n\nPurpose: ${specialist.purpose}\n\nStay within your specialist ownership. Write evidence-backed claims, assumptions, missing data, and confidence.\n`;
}

function renderEvalCases(blueprint) {
  return `# ${blueprint.agent_id} Eval Cases\n\nRequired case classes:\n\n${blueprint.eval.required_case_classes.map((caseClass) => `- ${caseClass}`).join("\n")}\n\n## Template\n\n- id:\n- category:\n- prompt:\n- expected_route:\n- expected_artifacts:\n- hard_fails:\n- answer_requirements:\n`;
}

function renderRubric(blueprint) {
  return `# ${blueprint.agent_id} Rubric\n\nEach dimension scores 0-2. Do not pass cases that hit hard failures.\n\n## Dimensions\n\n- Route correctness\n- Evidence grounding\n- Domain correctness\n- Tool boundary adherence\n- Actionability\n- Gap disclosure\n- Runtime reliability\n- Context economy\n\n## Hard failures\n\n${blueprint.eval.hard_failures.map((failure) => `- ${failure}`).join("\n")}\n`;
}

function renderVersionLedger(blueprint) {
  return `# ${blueprint.agent_id} Version Ledger\n\n## v0: AgentMother scaffold\n\n- Primary runtime: ${blueprint.runtime}\n- Runtime profiles: ${runtimeProfileIds(blueprint).join(", ") || "none"}\n- Main agent: ${blueprint.architecture.main_agent}\n- Latest commit: ${blueprint.release.latest_commit ?? "pending"}\n- Latest tag: ${blueprint.release.latest_tag ?? "pending"}\n\n## Known risks\n\n${blueprint.release.known_risks.map((risk) => `- ${risk}`).join("\n") || "- None recorded"}\n`;
}

function renderEvidenceIndex(blueprint) {
  return `# ${blueprint.agent_id} Evidence Index\n\n## Evidence stores\n\n${blueprint.evidence.stores.map((store) => `- ${store}`).join("\n")}\n\n## Required artifacts\n\n${blueprint.evidence.required_artifacts.map((artifact) => `- ${artifact}`).join("\n")}\n\n## Audit rules\n\n${blueprint.evidence.audit_rules.map((rule) => `- ${rule}`).join("\n")}\n`;
}

function renderQualityGates(blueprint) {
  return `# ${blueprint.agent_id} Quality Gates\n\n${blueprint.governance.quality_gates.map((gate) => `- [ ] ${gate}`).join("\n")}\n`;
}

function renderOpenClawReadme(blueprint) {
  return `# ${blueprint.agent_id} OpenClaw Scaffold\n\nThis directory is generated by AgentMo with \`--target openclaw\`. It turns the AgentMother blueprint into an OpenClaw-oriented workspace package.\n\n## Generated pieces\n\n- \`workspace/AGENTS.md\`: operating instructions loaded by OpenClaw sessions.\n- \`workspace/SOUL.md\`: persona, tone, and boundaries.\n- \`workspace/USER.md\`: user profile placeholder.\n- \`workspace/TOOLS.md\`: local tool conventions and evidence boundaries.\n- \`workspace/IDENTITY.md\`: visible identity fields.\n- \`workspace/skills/${blueprint.agent_id}/SKILL.md\`: domain skill derived from the blueprint.\n- \`config/openclaw.agent.patch.json\`: patch-shaped config fragment for \`~/.openclaw/openclaw.json\`.\n- \`runtime_contract.md\`: OpenClaw-specific runtime ownership and transfer contract.\n- \`RUNBOOK.md\`: manual setup and verification steps.\n\n## Runtime position\n\nThe generated OpenClaw scaffold is a runtime target. It does not overwrite the blueprint's primary runtime unless you change \`runtime\` to \`openclaw\` and certify it through evals.\n`;
}

function renderOpenClawRunbook(blueprint, workspaceDir) {
  return `# ${blueprint.agent_id} OpenClaw Runbook\n\n## 1. Review generated workspace\n\nGenerated workspace path:\n\n\`\`\`text\n${workspaceDir}\n\`\`\`\n\nReview these files before binding real channels:\n\n- \`workspace/AGENTS.md\`\n- \`workspace/SOUL.md\`\n- \`workspace/TOOLS.md\`\n- \`workspace/skills/${blueprint.agent_id}/SKILL.md\`\n\n## 2. Register the agent\n\nUse either the config patch in \`config/openclaw.agent.patch.json\` or the CLI path below.\n\n\`\`\`bash\nopenclaw agents add ${blueprint.agent_id} --workspace "${workspaceDir}" --non-interactive\nopenclaw agents list --bindings\n\`\`\`\n\n## 3. Bind channels explicitly\n\nDo not bind production channels until the workspace has passed dry-run review. Example only:\n\n\`\`\`bash\nopenclaw agents bind --agent ${blueprint.agent_id} --bind telegram:*\nopenclaw channels status --probe\n\`\`\`\n\n## 4. Verify sessions and evidence\n\n\`\`\`bash\nopenclaw sessions --agent ${blueprint.agent_id} --json\nopenclaw sessions --agent ${blueprint.agent_id} tail --tail 25\n\`\`\`\n\nKeep trajectory inspection bounded. Do not paste raw prompts, tool arguments, or tool result bodies into routine evidence.\n\n## 5. Certify before release\n\nRun the AgentMother eval suite for the target runtime, record the run in the version ledger, and disclose known risks before marking this runtime as certified.\n`;
}

function renderOpenClawRuntimeContract(blueprint) {
  const profile = findRuntimeProfile(blueprint, "openclaw");
  return `# ${blueprint.agent_id} OpenClaw Runtime Contract\n\n## Source profile\n\n- Runtime id: openclaw\n- Role: ${profile?.role ?? "unprofiled"}\n- Status: ${profile?.status ?? "unprofiled"}\n- Purpose: ${profile?.purpose ?? "No OpenClaw runtime profile recorded."}\n\n## Ownership table\n\n| Surface | Owner in OpenClaw target | AgentMother rule |\n| --- | --- | --- |\n| Model loop | OpenClaw embedded runtime unless provider/model policy selects a plugin runtime. | Record the selected runtime id; do not infer it from provider name. |\n| Canonical session history | OpenClaw session store under the selected agent scope. | Treat raw transcripts as audit artifacts, not normal prompt context. |\n| Workspace context | OpenClaw workspace files such as AGENTS.md, SOUL.md, USER.md, TOOLS.md, skills, memory. | Keep workspace private and version only non-secret guidance. |\n| Channel delivery | OpenClaw Gateway and channel bindings. | Treat channels as ingress/egress, not the domain genome. |\n| Dynamic tools and hooks | OpenClaw-owned tool loop and plugin hooks when supported by the active runtime. | Port hook behavior only when the target runtime exposes equivalent hooks. |\n| Evidence | Session summaries, trajectory tails, exports, eval records, release ledger. | Default to bounded summaries and explicit audit expansion. |\n\n## Evidence boundaries\n\n${renderStringList(profile?.evidence_boundaries ?? []) || "- No OpenClaw-specific evidence boundaries recorded."}\n\n## Transfer rules\n\n${renderStringList(profile?.transfer_rules ?? []) || "- No OpenClaw-specific transfer rules recorded."}\n\n## Source refs\n\n${renderStringList(profile?.source_refs ?? []) || "- No OpenClaw-specific source refs recorded."}\n\n## Hard failures inherited from blueprint\n\n${renderStringList(blueprint.domain_genome.hard_failures)}\n`;
}

function buildOpenClawConfigPatch(blueprint, workspaceDir) {
  return {
    note: "Merge manually into ~/.openclaw/openclaw.json; this is a patch-shaped fragment, not a full config.",
    agents: {
      list: [
        {
          id: blueprint.agent_id,
          name: identityName(blueprint),
          workspace: workspaceDir,
          skills: [blueprint.agent_id],
        },
      ],
    },
    bindings: [
      {
        agentId: blueprint.agent_id,
        match: {
          channel: "<channel>",
          accountId: "*",
        },
      },
    ],
  };
}

function renderOpenClawBindingExamples(blueprint) {
  return `# ${blueprint.agent_id} OpenClaw Channel Binding Examples\n\nUse bindings to route inbound channel traffic to this generated agent. These are examples, not production defaults.\n\n## Telegram all accounts\n\n\`\`\`bash\nopenclaw agents bind --agent ${blueprint.agent_id} --bind telegram:*\n\`\`\`\n\n## Discord specific account or guild alias\n\n\`\`\`bash\nopenclaw agents bind --agent ${blueprint.agent_id} --bind discord:<account-or-guild>\n\`\`\`\n\n## WhatsApp business account\n\n\`\`\`bash\nopenclaw agents bind --agent ${blueprint.agent_id} --bind whatsapp:biz\n\`\`\`\n\n## Verify\n\n\`\`\`bash\nopenclaw agents list --bindings\nopenclaw channels status --probe\n\`\`\`\n`;
}

function renderOpenClawAgents(blueprint) {
  return `# ${identityName(blueprint)} Operating Instructions\n\nYou are an OpenClaw runtime target generated from an AgentMother blueprint.\n\n## AgentMo pipeline\n\n${renderPipeline(blueprint)}\n\n## Domain\n\n${blueprint.domain_genome.domain}\n\n## Purpose\n\n${blueprint.domain_genome.purpose}\n\n## Routing modes\n\n${renderStringList(blueprint.architecture.routing_modes)}\n\n## Tool contracts\n\n${renderToolContracts(blueprint)}\n\n## Evidence policy\n\n${renderStringList(blueprint.evidence.audit_rules)}\n\n## Hard failures\n\n${renderStringList(blueprint.domain_genome.hard_failures)}\n\n## OpenClaw runtime rules\n\n- Keep provider, model, runtime, and channel as separate layers.\n- Treat Gateway/channel bindings as delivery surfaces, not as domain reasoning authority.\n- Keep session and trajectory evidence bounded by default.\n- Expand raw transcript, tool args, or tool results only for explicit audit requests.\n- Do not claim parity with the Pi runtime until this OpenClaw target has its own eval evidence.\n`;
}

function renderOpenClawSoul(blueprint) {
  return `# ${identityName(blueprint)} Soul\n\nTone: concise, evidence-backed, operational.\n\nPersonality boundary: act as a verifiable domain agent, not as a generic chat assistant.\n\nPrimary value: ${blueprint.domain_genome.purpose}\n\nAlways separate:\n\n- evidence-backed fact;\n- inference;\n- assumption;\n- missing data;\n- recommended next action.\n`;
}

function renderOpenClawUser(blueprint) {
  return `# User Context\n\nThis workspace was generated for the ${blueprint.agent_id} domain agent.\n\nFill in user-specific preferences here before production use:\n\n- Preferred language:\n- Preferred level of detail:\n- Approval boundaries:\n- Production channel constraints:\n- Sensitive data boundaries:\n`;
}

function renderOpenClawTools(blueprint) {
  return `# Tool Conventions\n\nTOOLS.md is guidance, not tool availability. OpenClaw tool availability is controlled by runtime configuration and policy.\n\n## Blueprint tool contracts\n\n${renderToolContracts(blueprint)}\n\n## Runtime evidence conventions\n\n- Prefer bounded evidence cards over raw stores.\n- Use session trajectory tails for progress inspection, not prompt reconstruction.\n- Do not expose raw tool arguments or results in normal answers.\n- Record failed or partial tool calls explicitly.\n`;
}

function renderOpenClawIdentity(blueprint) {
  return `# ${identityName(blueprint)}\n\nName: ${identityName(blueprint)}\n\nTheme: AgentMother-generated ${blueprint.domain_genome.domain} specialist\n\nEmoji: none\n\nAvatar: optional\n`;
}

function renderOpenClawSkill(blueprint) {
  return `---\nname: ${blueprint.agent_id}\ndescription: "Use for ${blueprint.domain_genome.domain}: ${blueprint.domain_genome.purpose}"\n---\n\n# ${blueprint.agent_id} Skill\n\nUse this skill when the user asks about ${blueprint.domain_genome.domain} or any required task class below.\n\n## Task classes\n\n${renderStringList(blueprint.domain_genome.task_classes)}\n\n## Routing modes\n\n${renderStringList(blueprint.architecture.routing_modes)}\n\n## Answer policy\n\n- Choose the lightest correct route.\n- Use the blueprint tool contracts as routing rules.\n- Cite bounded evidence artifacts when factual claims depend on tools.\n- Disclose missing data and partial failures.\n- Do not release or certify this OpenClaw target without eval evidence.\n`;
}

function renderOpenClawMemoryReadme(blueprint) {
  return `# ${blueprint.agent_id} Memory\n\nUse daily memory files only for durable, non-secret operational notes.\n\nDo not store:\n\n- API keys or OAuth tokens;\n- raw private chat dumps;\n- unrestricted session transcripts;\n- sensitive customer records.\n\nAgentMother evidence should remain bounded and auditable.\n`;
}

function renderRuntimeProfiles(blueprint) {
  const profiles = Array.isArray(blueprint.runtime_profiles) ? blueprint.runtime_profiles : [];
  if (profiles.length === 0) return "- No secondary runtime profiles recorded.";
  return profiles
    .map(
      (profile) =>
        `- ${profile.id} (${profile.role}, ${profile.status}): ${profile.purpose}\n  - Owned surfaces: ${profile.owned_surfaces.join(", ")}\n  - Evidence boundaries: ${profile.evidence_boundaries.join(", ")}${renderOptionalRuntimeProfileLines(profile)}`,
    )
    .join("\n");
}

function renderPipeline(blueprint) {
  const pipeline = blueprint.pipeline;
  return `### 1. Discover: find what to build

Purpose: ${pipeline.discover.purpose}

Data sources:
${renderStringList(pipeline.discover.data_sources)}

Database outputs:
${renderStringList(pipeline.discover.database_outputs)}

User-need inputs:
${renderStringList(pipeline.discover.user_need_inputs)}

Done when:
${renderStringList(pipeline.discover.done_when)}

### 2. Plan: decide how to build

Purpose: ${pipeline.plan.purpose}

Planning inputs:
${renderStringList(pipeline.plan.planning_inputs)}

Planning outputs:
${renderStringList(pipeline.plan.planning_outputs)}

Decision gates:
${renderStringList(pipeline.plan.decision_gates)}

Done when:
${renderStringList(pipeline.plan.done_when)}

### 3. Produce: program the agent

Purpose: ${pipeline.produce.purpose}

Coding tools:
${renderStringList(pipeline.produce.coding_tools)}

Runtime targets:
${renderStringList(pipeline.produce.runtime_targets)}

Generated outputs:
${renderStringList(pipeline.produce.generated_outputs)}

Verification steps:
${renderStringList(pipeline.produce.verification_steps)}

Done when:
${renderStringList(pipeline.produce.done_when)}`;
}

function renderOptionalRuntimeProfileLines(profile) {
  const lines = [];
  if (Array.isArray(profile.source_refs) && profile.source_refs.length > 0) {
    lines.push(`  - Source refs: ${profile.source_refs.join(", ")}`);
  }
  if (Array.isArray(profile.transfer_rules) && profile.transfer_rules.length > 0) {
    lines.push(`  - Transfer rules: ${profile.transfer_rules.join(", ")}`);
  }
  return lines.length > 0 ? `\n${lines.join("\n")}` : "";
}

function runtimeProfileIds(blueprint) {
  return Array.isArray(blueprint.runtime_profiles)
    ? blueprint.runtime_profiles.map((profile) => profile.id).filter((id) => typeof id === "string")
    : [];
}

function findRuntimeProfile(blueprint, id) {
  if (!Array.isArray(blueprint.runtime_profiles)) return undefined;
  return blueprint.runtime_profiles.find((profile) => profile && typeof profile === "object" && profile.id === id);
}

function renderToolContracts(blueprint) {
  return blueprint.tools
    .map(
      (tool) =>
        `### ${tool.name}\n\nPurpose: ${tool.purpose}\n\nAllowed when:\n${renderStringList(tool.allowed_when)}\n\nForbidden when:\n${renderStringList(tool.forbidden_when)}\n\nEvidence policy: ${tool.evidence_policy}`,
    )
    .join("\n\n");
}

function renderStringList(items) {
  return items.map((item) => `- ${item}`).join("\n");
}

function identityName(blueprint) {
  return blueprint.agent_id
    .split("-")
    .filter((part) => part.length > 0)
    .map((part) => `${part.slice(0, 1).toUpperCase()}${part.slice(1)}`)
    .join(" ");
}
