import { renderDigestBindings } from "./artifact-subjects.js";
import { OPENCLAW_TARGET_NODE_RANGE } from "./runtime-compatibility.js";

export function buildTargetFiles(blueprint, targetId) {
  const files = buildBaseFiles(blueprint);
  if (targetId === "openclaw") addOpenClawFiles(files, blueprint);
  return files;
}

export function buildBaseFiles(blueprint) {
  const files = new Map([
    ["README.md", renderReadme(blueprint)],
    ["agent_policy.json", JSON.stringify(buildAgentPolicy(blueprint), null, 2) + "\n"],
    [`agents/${blueprint.architecture.main_agent}.md`, renderMainAgent(blueprint)],
    ["evals/CASES.md", renderEvalCases(blueprint)],
    ["evals/RUBRIC.md", renderRubric(blueprint)],
    ["history/VERSION_LEDGER.md", renderVersionLedger(blueprint)],
    ["history/EVIDENCE_INDEX.md", renderEvidenceIndex(blueprint)],
    ["governance/QUALITY_GATES.md", renderQualityGates(blueprint)],
  ]);

  for (const specialist of blueprint.architecture.specialists ?? []) {
    files.set(`agents/${specialist.id}.md`, renderSpecialistAgent(blueprint, specialist));
  }

  return files;
}

export function addOpenClawFiles(files, blueprint) {
  const workspaceDir = "openclaw/workspace";
  files.set("openclaw/README.md", renderOpenClawReadme(blueprint));
  files.set("openclaw/RUNBOOK.md", renderRegistryBoundOpenClawRunbook(blueprint, workspaceDir));
  files.set("openclaw/runtime_contract.md", renderOpenClawRuntimeContract(blueprint));
  files.set("openclaw/config/openclaw.agent.patch.json", JSON.stringify(buildOpenClawConfigPatch(blueprint, workspaceDir), null, 2) + "\n");
  files.set("openclaw/config/channel-bindings.examples.md", renderOpenClawBindingExamples(blueprint));
  files.set("openclaw/workspace/AGENTS.md", renderOpenClawAgents(blueprint));
  files.set("openclaw/workspace/SOUL.md", renderOpenClawSoul(blueprint));
  files.set("openclaw/workspace/USER.md", renderOpenClawUser(blueprint));
  files.set("openclaw/workspace/TOOLS.md", renderOpenClawTools(blueprint));
  files.set("openclaw/workspace/IDENTITY.md", renderOpenClawIdentity(blueprint));
  files.set(`openclaw/workspace/skills/${blueprint.agent_id}/SKILL.md`, renderOpenClawSkill(blueprint));
  files.set("openclaw/workspace/memory/README.md", renderOpenClawMemoryReadme(blueprint));
}

function buildAgentPolicy(blueprint) {
  return {
    version: "0.1",
    agent_id: blueprint.agent_id,
    runtime: blueprint.runtime,
    runtime_profiles: (blueprint.runtime_profiles ?? []).map(portableRuntimeProfile),
    status: blueprint.status,
    boundaries: {
      domain: blueprint.domain_genome.domain,
      purpose: blueprint.domain_genome.purpose,
      hard_failures: blueprint.domain_genome.hard_failures,
    },
    routing_modes: blueprint.architecture.routing_modes,
    tools: blueprint.tools.map((tool) => ({
      name: tool.name,
      purpose: tool.purpose,
      allowed_when: tool.allowed_when,
      forbidden_when: tool.forbidden_when,
      evidence_policy: tool.evidence_policy,
    })),
    evidence: blueprint.evidence,
    eval: blueprint.eval,
    governance: blueprint.governance,
  };
}

function renderReadme(blueprint) {
  return `# ${blueprint.agent_id}\n\nGenerated by AgentMo.\n\n## Purpose\n\n${blueprint.domain_genome.purpose}\n\n## AgentMo pipeline\n\n${renderPipeline(blueprint)}\n\n## Produce-internal gates\n\nBirth, domain eval, delivery, and observe/evolve remain gates or proposals inside Produce; they are not additional top-level lifecycle stages.\n\n## Runtime\n\n- Primary runtime: ${blueprint.runtime}\n- Main agent: ${blueprint.architecture.main_agent}\n- Status: ${blueprint.status}\n\n## Runtime profiles\n\n${renderRuntimeProfiles(blueprint)}\n\n## Required quality gates\n\n${blueprint.governance.quality_gates.map((gate) => `- ${gate}`).join("\n")}\n\n## Do not release unless\n\n- Discovery data and user needs are captured.\n- Planning artifacts and decision gates are explicit.\n- Tool contracts are explicit.\n- Eval cases exist for each required case class.\n- Domain-eval evidence exists before any bounded domain-quality claim.\n- Delivery-report evidence aggregates the build/run/birth/domain artifacts without self-certifying runtime, production, or domain-wide claims.\n- Evidence artifacts are bounded and auditable.\n- Known risks are recorded.\n`;
}

function renderMainAgent(blueprint) {
  const tools = blueprint.tools.map((tool) => tool.name).join(",");
  return `---\nname: ${blueprint.architecture.main_agent}\ndescription: "Main orchestrator for ${blueprint.agent_id}."\ntools: ${tools}\n---\n\n# ${blueprint.architecture.main_agent}\n\nYou are the main orchestrator for ${blueprint.agent_id}.\n\n## Domain\n\n${blueprint.domain_genome.domain}\n\n## Purpose\n\n${blueprint.domain_genome.purpose}\n\n## Routing modes\n\n${blueprint.architecture.routing_modes.map((mode) => `- ${mode}`).join("\n")}\n\n## Hard failures\n\n${blueprint.domain_genome.hard_failures.map((failure) => `- ${failure}`).join("\n")}\n\n## Evidence policy\n\nUse bounded evidence packets by default. Expand raw artifacts only for explicit audit requests.\n`;
}

function renderSpecialistAgent(blueprint, specialist) {
  return `---\nname: ${specialist.id}\ndescription: "Specialist for ${blueprint.agent_id}: ${specialist.purpose}"\n---\n\n# ${specialist.id}\n\nPurpose: ${specialist.purpose}\n\nStay within your specialist ownership. Write evidence-backed claims, assumptions, missing data, and confidence.\n`;
}

function renderEvalCases(blueprint) {
  return `# ${blueprint.agent_id} Eval Cases\n\nRequired case classes:\n\n${blueprint.eval.required_case_classes.map((caseClass) => `- ${caseClass}`).join("\n")}\n\n## Domain-eval boundary\n\nUse these cases as the source for bounded case-suite domain-quality evidence with \`agentmo domain-eval\`. Deterministic fixtures prove only the covered sample behavior; they are not production, domain-wide, or live-channel certification.\n\n## Template\n\n- id:\n- category:\n- prompt:\n- expected_route:\n- expected_artifacts:\n- bounded_evidence_refs:\n- hard_fails:\n- answer_requirements:\n`;
}

function renderRubric(blueprint) {
  return `# ${blueprint.agent_id} Rubric\n\nEach dimension scores 0-2. Do not pass cases that hit hard failures.\n\n\`agentmo domain-eval\` can turn rubric-scored, bounded cases into independent case-suite domain-quality evidence. It does not certify runtime execution, production approval, or domain-wide quality.\n\n## Dimensions\n\n- Route correctness\n- Evidence grounding\n- Domain correctness\n- Tool boundary adherence\n- Actionability\n- Gap disclosure\n- Runtime reliability\n- Context economy\n\n## Hard failures\n\n${blueprint.eval.hard_failures.map((failure) => `- ${failure}`).join("\n")}\n`;
}

function renderVersionLedger(blueprint) {
  return `# ${blueprint.agent_id} Version Ledger\n\n## v0: AgentMo scaffold\n\n- Primary runtime: ${blueprint.runtime}\n- Runtime profiles: ${runtimeProfileIds(blueprint).join(", ") || "none"}\n- Main agent: ${blueprint.architecture.main_agent}\n- Latest commit: ${blueprint.release.latest_commit ?? "pending"}\n- Latest tag: ${blueprint.release.latest_tag ?? "pending"}\n\n## Known risks\n\n${blueprint.release.known_risks.map((risk) => `- ${risk}`).join("\n") || "- None recorded"}\n`;
}

function renderEvidenceIndex(blueprint) {
  return `# ${blueprint.agent_id} Evidence Index\n\n## Evidence stores\n\n${blueprint.evidence.stores.map((store) => `- ${store}`).join("\n")}\n\n## Required artifacts\n\n${blueprint.evidence.required_artifacts.map((artifact) => `- ${artifact}`).join("\n")}\n\n## Delivery closure artifacts\n\n- \`agentmo birth-report\`: mechanism/runtime birth evidence only; not domain quality or production approval.\n- \`agentmo domain-eval\`: independent bounded case-suite domain-quality evidence; not runtime, production, or domain-wide certification.\n- \`agentmo delivery-report\`: aggregate/revalidation report over source artifacts; not a replacement for source evidence and not self-certification.\n\n## Audit rules\n\n${blueprint.evidence.audit_rules.map((rule) => `- ${rule}`).join("\n")}\n`;
}

function renderQualityGates(blueprint) {
  return `# ${blueprint.agent_id} Quality Gates\n\n${blueprint.governance.quality_gates.map((gate) => `- [ ] ${gate}`).join("\n")}\n`;
}

function renderOpenClawReadme(blueprint) {
  return `# ${blueprint.agent_id} OpenClaw Scaffold\n\nThis directory is generated by AgentMo with \`--target openclaw\`. It turns the AgentMo blueprint into an OpenClaw-oriented workspace package.\n\n## Generated pieces\n\n- \`workspace/AGENTS.md\`: operating instructions loaded by OpenClaw sessions.\n- \`workspace/SOUL.md\`: persona, tone, and boundaries.\n- \`workspace/USER.md\`: user profile placeholder.\n- \`workspace/TOOLS.md\`: local tool conventions and evidence boundaries.\n- \`workspace/IDENTITY.md\`: visible identity fields.\n- \`workspace/skills/${blueprint.agent_id}/SKILL.md\`: domain skill derived from the blueprint.\n- \`config/openclaw.agent.patch.json\`: patch-shaped fragment for \`<openclaw-config>/openclaw.json\`.\n- \`runtime_contract.md\`: OpenClaw-specific runtime ownership and transfer contract.\n- \`RUNBOOK.md\`: manual setup and verification steps.\n\n## Runtime position\n\nThe generated OpenClaw scaffold is a runtime target. It does not overwrite the blueprint's primary runtime unless you change \`runtime\` to \`openclaw\` and certify it through evals.\n`;
}

function renderRegistryBoundOpenClawRunbook(blueprint, workspaceDir) {
  const blueprintFile = `examples/${blueprint.agent_id}.agentmo.json`;
  const blueprintBindings = (command, optional = {}) => renderDigestBindings(command, {
    blueprint: "$BLUEPRINT",
    ...optional,
  });
  return `# ${blueprint.agent_id} OpenClaw Runbook

This runbook is evidence-first. Runtime evidence does not certify OpenClaw domain parity or change blueprint status. Birth, eval, delivery, and observe are Produce-internal gates or proposals, not extra lifecycle stages.

OpenClaw target mutations require Node.js \`${OPENCLAW_TARGET_NODE_RANGE}\`. The authoritative check is \`node ./bin/agentmo.js runtime-check --target openclaw\`; copied instructions must run it before mutation instead of implementing their own predicate.

## 1. Review generated workspace

Generated workspace: \`${workspaceDir}\`.

Review \`workspace/AGENTS.md\`, \`workspace/SOUL.md\`, \`workspace/TOOLS.md\`, and \`workspace/skills/${blueprint.agent_id}/SKILL.md\` before binding real channels.

## 2. Produce an admitted runtime plan

\`run-plan\` is non-live planning. Each \`--digest\` below hashes the exact file bytes inside the invocation; it does not hash parsed JSON or reuse recorded provenance.

\`\`\`bash
BLUEPRINT="${blueprintFile}"
RUNTIME_PLAN="<temporary-root>/agentmo-${blueprint.agent_id}-runtime-plan.json"
node ./bin/agentmo.js run-plan "$BLUEPRINT" ${blueprintBindings("run-plan")} --target "openclaw" --workspace "${workspaceDir}" --agent "${blueprint.agent_id}" --provider "openai" --model "gpt-5.5" --thinking "off" --channel "local-cli" --transport "local" --message "Say exactly: ok" --json > "$RUNTIME_PLAN"
\`\`\`

For an OpenClaw source checkout, add \`--openclaw-source-root "<openclaw-source-root>"\` to both \`run-plan\` and \`run\`.

The runtime plan keeps provider, model, thinking, runtime, channel, selector, transport, fallbackFrom, fallbackEvidence, sandboxScope as separate fields. \`run\` allocates a fresh run-scoped execution unless an explicit selector is supplied; same-session replay requires explicit \`--resume-session\`. Multiline or over-limit prompts use \`--message-file\`.

## 3. Write managed run evidence

\`\`\`bash
RUN_OUT="<temporary-root>/agentmo-${blueprint.agent_id}-runs"
node ./bin/agentmo.js run "$RUNTIME_PLAN" ${renderDigestBindings("run", { "runtime-plan": "$RUNTIME_PLAN" })} --workspace "${workspaceDir}" --message "Say exactly: ok" --out "$RUN_OUT" --json
RUN_STATE="$RUN_OUT/runs/<run_id>/agentmo-run-state.json"
node ./bin/agentmo.js status "$BLUEPRINT" ${blueprintBindings("status", { "run-state": "$RUN_STATE" })} --run-state "$RUN_STATE" --json
\`\`\`

The default run is non-live and records \`executed:false\` with \`status:"declared"\`. It does not certify the runtime.

## 4. Report, replay, evaluate, and observe

\`\`\`bash
RUN_EVAL="<temporary-root>/agentmo-${blueprint.agent_id}-run-eval.json"
OBSERVATION="<temporary-root>/agentmo-${blueprint.agent_id}-observation.json"
node ./bin/agentmo.js run-report "$RUN_STATE" ${renderDigestBindings("run-report", { "run-state": "$RUN_STATE" })} --json
node ./bin/agentmo.js replay-run "$RUN_STATE" ${renderDigestBindings("replay-run", { "run-state": "$RUN_STATE" })} --out "<temporary-root>/agentmo-${blueprint.agent_id}-replay" --json
node ./bin/agentmo.js run-eval "$RUN_STATE" ${renderDigestBindings("run-eval", { "run-state": "$RUN_STATE" })} --expect-status "declared" --json > "$RUN_EVAL"
node ./bin/agentmo.js observe-run "$RUN_STATE" ${renderDigestBindings("observe-run", { "run-state": "$RUN_STATE" })} --out "$OBSERVATION" --json
node ./bin/agentmo.js observe "$OBSERVATION" ${renderDigestBindings("observe", { observation: "$OBSERVATION" })} --json
\`\`\`

\`observe-run\` is proposal-only and must not mutate the source run-state, blueprint, scaffold, runtime, or evals.

## 5. Close bounded domain and delivery evidence

\`\`\`bash
BUILD_STATE="<scaffold-root>/agentmo-build-state.json"
DOMAIN_CASES="<domain-cases.json>"
BIRTH_REPORT="<temporary-root>/agentmo-${blueprint.agent_id}-birth-report.json"
DOMAIN_EVAL="<temporary-root>/agentmo-${blueprint.agent_id}-domain-eval.json"
DELIVERY_REPORT="<temporary-root>/agentmo-${blueprint.agent_id}-delivery-report.json"
node ./bin/agentmo.js birth-report "$BLUEPRINT" ${blueprintBindings("birth-report", { "build-state": "$BUILD_STATE", "run-state": "$RUN_STATE", "run-eval": "$RUN_EVAL" })} --build-state "$BUILD_STATE" --run-state "$RUN_STATE" --run-eval "$RUN_EVAL" --expect-status "declared" --json > "$BIRTH_REPORT"
node ./bin/agentmo.js domain-eval "$BLUEPRINT" ${blueprintBindings("domain-eval", { "domain-cases": "$DOMAIN_CASES" })} --cases "$DOMAIN_CASES" --target "openclaw" --json > "$DOMAIN_EVAL"
node ./bin/agentmo.js delivery-report "$BLUEPRINT" ${blueprintBindings("delivery-report", { "build-state": "$BUILD_STATE", "run-state": "$RUN_STATE", "run-eval": "$RUN_EVAL", "birth-report": "$BIRTH_REPORT", "domain-eval": "$DOMAIN_EVAL" })} --build-state "$BUILD_STATE" --run-state "$RUN_STATE" --run-eval "$RUN_EVAL" --birth-report "$BIRTH_REPORT" --domain-eval "$DOMAIN_EVAL" --json > "$DELIVERY_REPORT"
\`\`\`

domain-eval fixtures certify only their bounded case suite. Delivery aggregation does not self-certify runtime, domain-wide quality, production approval, or customer-support readiness.

## 6. Optional isolated live local run

Live execution is explicit opt-in. Use isolated state; do not use production OpenClaw state for this smoke.

\`\`\`bash
node ./bin/agentmo.js runtime-check --target openclaw &&
RUN_ID="$(date +%Y%m%dT%H%M%S)-${blueprint.agent_id}-live" &&
export OPENCLAW_STATE_DIR="<temporary-root>/agentmo-openclaw-state-$RUN_ID" &&
WORKSPACE="<temporary-root>/agentmo-openclaw-workspace-$RUN_ID" &&
RUN_OUT="<temporary-root>/agentmo-openclaw-runs-$RUN_ID" &&
RUNTIME_PLAN="$RUN_OUT/agentmo-runtime-plan.json" &&
mkdir -p "$OPENCLAW_STATE_DIR" "$WORKSPACE" "$RUN_OUT" &&
node ./bin/agentmo.js run-plan "$BLUEPRINT" ${blueprintBindings("run-plan")} --target "openclaw" --workspace "$WORKSPACE" --openclaw-state-dir "$OPENCLAW_STATE_DIR" --agent "${blueprint.agent_id}" --provider "openai" --model "gpt-5.5" --thinking "off" --channel "local-cli" --transport "local" --message "Say exactly: ok" --json > "$RUNTIME_PLAN" &&
node ./bin/agentmo.js run "$RUNTIME_PLAN" ${renderDigestBindings("run", { "runtime-plan": "$RUNTIME_PLAN" })} --workspace "$WORKSPACE" --openclaw-state-dir "$OPENCLAW_STATE_DIR" --message "Say exactly: ok" --out "$RUN_OUT" --live --json
\`\`\`

The preflight above authorizes only the current process/runtime pairing. It is not live-success or domain-quality evidence.

## 7. Register and inspect explicitly

\`\`\`bash
node ./bin/agentmo.js runtime-check --target openclaw &&
openclaw agents add ${blueprint.agent_id} --workspace "${workspaceDir}" --non-interactive &&
openclaw agents list --bindings &&
openclaw sessions --agent ${blueprint.agent_id} --json
\`\`\`

Do not bind production channels until isolated live smoke, bounded domain eval, delivery evidence, and human review are complete. Keep trajectory inspection bounded; routine evidence excludes raw prompts, transcripts, tool arguments, tool results, and credential values.
`;
}


function renderOpenClawRuntimeContract(blueprint) {
  const sourceProfile = findRuntimeProfile(blueprint, "openclaw");
  const profile = sourceProfile ? portableRuntimeProfile(sourceProfile) : undefined;
  return `# ${blueprint.agent_id} OpenClaw Runtime Contract\n\n## Source profile\n\n- Runtime id: openclaw\n- Role: ${profile?.role ?? "unprofiled"}\n- Status: ${profile?.status ?? "unprofiled"}\n- Purpose: ${profile?.purpose ?? "No OpenClaw runtime profile recorded."}\n\n## Ownership table\n\n| Surface | Owner in OpenClaw target | AgentMo rule |\n| --- | --- | --- |\n| Model loop | OpenClaw embedded runtime unless provider/model policy selects a plugin runtime. | Record the selected runtime id; do not infer it from provider name. |\n| Canonical session history | OpenClaw session store under the selected agent scope. | Treat raw transcripts as audit artifacts, not normal prompt context. |\n| Workspace context | OpenClaw workspace files such as AGENTS.md, SOUL.md, USER.md, TOOLS.md, skills, memory. | Keep workspace private and version only non-secret guidance. |\n| Channel delivery | OpenClaw Gateway and channel bindings. | Treat channels as ingress/egress, not the domain genome. |\n| Dynamic tools and hooks | OpenClaw-owned tool loop and plugin hooks when supported by the active runtime. | Port hook behavior only when the target runtime exposes equivalent hooks. |\n| Evidence | Session summaries, trajectory tails, exports, eval records, release ledger. | Default to bounded summaries and explicit audit expansion. |\n\n## Evidence boundaries\n\n${renderStringList(profile?.evidence_boundaries ?? []) || "- No OpenClaw-specific evidence boundaries recorded."}\n\n## Transfer rules\n\n${renderStringList(profile?.transfer_rules ?? []) || "- No OpenClaw-specific transfer rules recorded."}\n\n## Source refs\n\n${renderStringList(profile?.source_refs ?? []) || "- No OpenClaw-specific source refs recorded."}\n\n## Hard failures inherited from blueprint\n\n${renderStringList(blueprint.domain_genome.hard_failures)}\n`;
}

function buildOpenClawConfigPatch(blueprint, workspaceDir) {
  return {
    note: "Merge manually into <openclaw-config>/openclaw.json; this is a patch-shaped fragment, not a full config.",
    agents: {
      list: [
        {
          id: blueprint.agent_id,
          name: identityName(blueprint),
          workspace: workspaceDir,
          skills: [blueprint.agent_id],
        },
      ],
    },
    bindings: [
      {
        agentId: blueprint.agent_id,
        match: {
          channel: "<channel>",
          accountId: "*",
        },
      },
    ],
  };
}

function renderOpenClawBindingExamples(blueprint) {
  return `# ${blueprint.agent_id} OpenClaw Channel Binding Examples\n\nUse bindings to route inbound channel traffic to this generated agent. These are examples, not production defaults. OpenClaw mutations require Node.js \`${OPENCLAW_TARGET_NODE_RANGE}\`; the AgentMo runtime-check command below is the sole authorization predicate.\n\n## Telegram all accounts\n\n\`\`\`bash\nnode ./bin/agentmo.js runtime-check --target openclaw &&\nopenclaw agents bind --agent ${blueprint.agent_id} --bind telegram:*\n\`\`\`\n\n## Discord specific account or guild alias\n\n\`\`\`bash\nnode ./bin/agentmo.js runtime-check --target openclaw &&\nopenclaw agents bind --agent ${blueprint.agent_id} --bind discord:<account-or-guild>\n\`\`\`\n\n## WhatsApp business account\n\n\`\`\`bash\nnode ./bin/agentmo.js runtime-check --target openclaw &&\nopenclaw agents bind --agent ${blueprint.agent_id} --bind whatsapp:biz\n\`\`\`\n\n## Verify\n\n\`\`\`bash\nopenclaw agents list --bindings\nopenclaw channels status --probe\n\`\`\`\n`;
}

function renderOpenClawAgents(blueprint) {
  return `# ${identityName(blueprint)} Operating Instructions\n\nYou are an OpenClaw runtime target generated from an AgentMo blueprint.\n\n## AgentMo pipeline\n\n${renderPipeline(blueprint)}\n\n## Domain\n\n${blueprint.domain_genome.domain}\n\n## Purpose\n\n${blueprint.domain_genome.purpose}\n\n## Routing modes\n\n${renderStringList(blueprint.architecture.routing_modes)}\n\n## Tool contracts\n\n${renderToolContracts(blueprint)}\n\n## Evidence policy\n\n${renderStringList(blueprint.evidence.audit_rules)}\n\n## Hard failures\n\n${renderStringList(blueprint.domain_genome.hard_failures)}\n\n## OpenClaw runtime rules\n\n- Keep provider, model, runtime, and channel as separate layers.\n- Treat Gateway/channel bindings as delivery surfaces, not as domain reasoning authority.\n- Keep session and trajectory evidence bounded by default.\n- Expand raw transcript, tool args, or tool results only for explicit audit requests.\n- Do not claim parity with the Pi runtime until this OpenClaw target has its own eval evidence.\n`;
}

function renderOpenClawSoul(blueprint) {
  return `# ${identityName(blueprint)} Soul\n\nTone: concise, evidence-backed, operational.\n\nPersonality boundary: act as a verifiable domain agent, not as a generic chat assistant.\n\nPrimary value: ${blueprint.domain_genome.purpose}\n\nAlways separate:\n\n- evidence-backed fact;\n- inference;\n- assumption;\n- missing data;\n- recommended next action.\n`;
}

function renderOpenClawUser(blueprint) {
  return `# User Context\n\nThis workspace was generated for the ${blueprint.agent_id} domain agent.\n\nFill in user-specific preferences here before production use:\n\n- Preferred language:\n- Preferred level of detail:\n- Approval boundaries:\n- Production channel constraints:\n- Sensitive data boundaries:\n`;
}

function renderOpenClawTools(blueprint) {
  return `# Tool Conventions\n\nTOOLS.md is guidance, not tool availability. OpenClaw tool availability is controlled by runtime configuration and policy.\n\n## Blueprint tool contracts\n\n${renderToolContracts(blueprint)}\n\n## Runtime evidence conventions\n\n- Prefer bounded evidence cards over raw stores.\n- Use session trajectory tails for progress inspection, not prompt reconstruction.\n- Do not expose raw tool arguments or results in normal answers.\n- Record failed or partial tool calls explicitly.\n`;
}

function renderOpenClawIdentity(blueprint) {
  return `# ${identityName(blueprint)}\n\nName: ${identityName(blueprint)}\n\nTheme: AgentMo-generated ${blueprint.domain_genome.domain} specialist\n\nEmoji: none\n\nAvatar: optional\n`;
}

function renderOpenClawSkill(blueprint) {
  return `---\nname: ${blueprint.agent_id}\ndescription: "Use for ${blueprint.domain_genome.domain}: ${blueprint.domain_genome.purpose}"\n---\n\n# ${blueprint.agent_id} Skill\n\nUse this skill when the user asks about ${blueprint.domain_genome.domain} or any required task class below.\n\n## Task classes\n\n${renderStringList(blueprint.domain_genome.task_classes)}\n\n## Routing modes\n\n${renderStringList(blueprint.architecture.routing_modes)}\n\n## Answer policy\n\n- Choose the lightest correct route.\n- Use the blueprint tool contracts as routing rules.\n- Cite bounded evidence artifacts when factual claims depend on tools.\n- Disclose missing data and partial failures.\n- Do not release or certify this OpenClaw target without eval evidence.\n`;
}

function renderOpenClawMemoryReadme(blueprint) {
  return `# ${blueprint.agent_id} Memory\n\nUse daily memory files only for durable, non-secret operational notes.\n\nDo not store:\n\n- API keys or OAuth tokens;\n- raw private chat dumps;\n- unrestricted session transcripts;\n- sensitive customer records.\n\nAgentMo evidence should remain bounded and auditable.\n`;
}

function renderRuntimeProfiles(blueprint) {
  const profiles = Array.isArray(blueprint.runtime_profiles) ? blueprint.runtime_profiles : [];
  if (profiles.length === 0) return "- No secondary runtime profiles recorded.";
  return profiles
    .map((sourceProfile) => {
      const profile = portableRuntimeProfile(sourceProfile);
      return `- ${profile.id} (${profile.role}, ${profile.status}): ${profile.purpose}\n  - Owned surfaces: ${profile.owned_surfaces.join(", ")}\n  - Evidence boundaries: ${profile.evidence_boundaries.join(", ")}${renderOptionalRuntimeProfileLines(profile)}`;
    })
    .join("\n");
}

function renderPipeline(blueprint) {
  const pipeline = blueprint.pipeline;
  return `### 1. Discover: find what to build

Purpose: ${pipeline.discover.purpose}

Data sources:
${renderStringList(pipeline.discover.data_sources)}

Database outputs:
${renderStringList(pipeline.discover.database_outputs)}

User-need inputs:
${renderStringList(pipeline.discover.user_need_inputs)}

Done when:
${renderStringList(pipeline.discover.done_when)}

### 2. Plan: decide how to build

Purpose: ${pipeline.plan.purpose}

Planning inputs:
${renderStringList(pipeline.plan.planning_inputs)}

Planning outputs:
${renderStringList(pipeline.plan.planning_outputs)}

Decision gates:
${renderStringList(pipeline.plan.decision_gates)}

Done when:
${renderStringList(pipeline.plan.done_when)}

### 3. Produce: program the agent

Purpose: ${pipeline.produce.purpose}

Coding tools:
${renderStringList(pipeline.produce.coding_tools)}

Runtime targets:
${renderStringList(pipeline.produce.runtime_targets)}

Generated outputs:
${renderStringList(pipeline.produce.generated_outputs)}

Verification steps:
${renderStringList(pipeline.produce.verification_steps.map(portableRuntimeInstruction))}

Done when:
${renderStringList(pipeline.produce.done_when)}`;
}

function renderOptionalRuntimeProfileLines(profile) {
  const lines = [];
  if (Array.isArray(profile.source_refs) && profile.source_refs.length > 0) {
    lines.push(`  - Source refs: ${profile.source_refs.join(", ")}`);
  }
  if (Array.isArray(profile.transfer_rules) && profile.transfer_rules.length > 0) {
    lines.push(`  - Transfer rules: ${profile.transfer_rules.join(", ")}`);
  }
  return lines.length > 0 ? `\n${lines.join("\n")}` : "";
}

function runtimeProfileIds(blueprint) {
  return Array.isArray(blueprint.runtime_profiles)
    ? blueprint.runtime_profiles.map((profile) => profile.id).filter((id) => typeof id === "string")
    : [];
}

function findRuntimeProfile(blueprint, id) {
  if (!Array.isArray(blueprint.runtime_profiles)) return undefined;
  return blueprint.runtime_profiles.find((profile) => profile && typeof profile === "object" && profile.id === id);
}

function renderToolContracts(blueprint) {
  return blueprint.tools
    .map(
      (tool) =>
        `### ${tool.name}\n\nPurpose: ${tool.purpose}\n\nAllowed when:\n${renderStringList(tool.allowed_when)}\n\nForbidden when:\n${renderStringList(tool.forbidden_when)}\n\nEvidence policy: ${tool.evidence_policy}`,
    )
    .join("\n\n");
}

function renderStringList(items) {
  return items.map((item) => `- ${item}`).join("\n");
}

function identityName(blueprint) {
  return blueprint.agent_id
    .split("-")
    .filter((part) => part.length > 0)
    .map((part) => `${part.slice(0, 1).toUpperCase()}${part.slice(1)}`)
    .join(" ");
}

function portableRuntimeProfile(profile) {
  return Object.fromEntries(
    Object.entries(profile).map(([key, value]) => {
      if (typeof value === "string") return [key, portableRuntimeInstruction(value)];
      if (Array.isArray(value)) {
        return [key, value.map((item) => {
          if (typeof item !== "string") return item;
          return key === "source_refs" ? portableSourceRef(item) : portableRuntimeInstruction(item);
        })];
      }
      return [key, value];
    }),
  );
}

function portableRuntimeInstruction(value) {
  return String(value)
    .replace(/~\/[A-Za-z0-9._/-]+/gu, "<home-relative-path>")
    .replace(/(^|[\s"'`=(])\/[A-Za-z0-9._-]+(?:\/[A-Za-z0-9._${}-]+)+/gmu, "$1<runtime-path>")
    .replace(/\b[A-Za-z]:[\\/][^\s"'`<>),\]}]+/gu, "<runtime-path>");
}

function portableSourceRef(value) {
  const text = String(value);
  const basename = /(?:^|[\\/])([^\\/]+@[a-f0-9]{7,64})$/u.exec(text)?.[1];
  return basename ?? portableRuntimeInstruction(text);
}
